/*
 * AppConstants
 * These are the variables that determine what our central data store (reducer.js)
 * changes in our state. When you add a new action, you have to add a new constant here
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'YOUR_ACTION_CONSTANT';
 */
export const UPDATE_SIGNUP_FORM = 'UPDATE_SIGNUP_FORM';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_SIGNUP_ERRORS = 'UPDATE_SIGNUP_ERRORS';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const UPDATE_LOGIN_ERRORS = 'UPDATE_LOGIN_ERRORS';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_AUTH_AS_FALSE = 'SET_AUTH_AS_FALSE';
export const SET_USER_NAME_AS_FALSE = 'SET_USER_NAME_AS_FALSE';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_ID_AS_FALSE = 'SET_USER_ID_AS_FALSE';
export const UPDATE_APPLY_STEP_ONE = 'UPDATE_APPLY_STEP_ONE';
export const UPDATE_APPLY_STEP_TWO = 'UPDATE_APPLY_STEP_TWO';
export const UPDATE_APPLY_STEP_THREE = 'UPDATE_APPLY_STEP_THREE';
export const UPDATE_APPLY_STEP_FOUR = 'UPDATE_APPLY_STEP_FOUR';
export const SET_CURRENT_APPLY_STEP = 'SET_CURRENT_APPLY_STEP';
export const SET_APPLICATION_COMPLETENESS = 'SET_APPLICATION_COMPLETENESS';
export const UPDATE_USER_UPDATING_STATUS = 'UPDATE_USER_UPDATING_STATUS';
export const UPDATE_APPLY_ERRORS = 'UPDATE_APPLY_ERRORS';
export const UPDATE_MOBILE_MENU_STATUS ='UPDATE_MOBILE_MENU_STATUS';
export const UPDATE_SUBMITTED_VIEW = 'UPDATE_SUBMITTED_VIEW';
export const UPDATE_FORGOT_PASSWORD_FORM = 'UPDATE_FORGOT_PASSWORD_FORM';
export const UPDATE_VOLUNTEER_FORM = 'UPDATE_VOLUNTEER_FORM';
export const UPDATE_VOLUNTEER_ERRORS = 'UPDATE_VOLUNTEER_ERRORS';
